### ISSUE TITLE
Create insert album sql script

### ISSUE THREAD

**Issue by TarasPaniuta** [TeamPaniuta/TrackMyWords#84]
#71

**Comment by ajain92** [comment]
INSERT INTO Album (album_id, title, cover, release_date) VALUES (album_id,'title','cover','release_date');

values( parameter) = variable assigned

**Comment by ajain92** [comment]
re-opening this task 
i closed this by mistake

**Comment by ajain92** [comment]
waiting for connected tasks to be completed for testing

**Comment by ajain92** [comment]
fc1cf5b8cce3d96557571413bd0328b2c003cda9
