### ISSUE TITLE
Create insert artist_album sql script

### ISSUE THREAD

**Issue by TarasPaniuta** [TeamPaniuta/TrackMyWords#86]
#71

**Comment by ajain92** [comment]
INSERT INTO Artist_Album (artist_album_id, album_id, artist_id) VALUES ('artist_album_id','album_id','artist_id');

Values(parameter) = variable assigned

**Comment by ajain92** [comment]
waiting for connected tasks to be completed for testing

**Comment by ajain92** [comment]
fc1cf5b8cce3d96557571413bd0328b2c003cda9
